[package]
name = "gmofg-proxy-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
gmofg-proxy-application = { path = "../application" }
gmofg-proxy-domain = { path = "../domain" }
gmofg-proxy-product-api = { path = "../product-api" }
gmofg-proxy-runtime = { path = "../proxy" }
p12-keystore.workspace = true
parking_lot.workspace = true
rcgen.workspace = true
ring.workspace = true
rusqlite.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
x509-parser.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
security-framework.workspace = true

[dev-dependencies]
gmofg-proxy-product-payment = { path = "../product-payment" }

[lints]
workspace = true
