api = 1

[package]
id = "nuvei-tango-json-rhai"
name = "Nuvei Tango JSON Read-Only"
version = "1.0.0"

[document.upstream]
schema = "document.toml"
display = "display_upstream"

[document.downstream]
schema = "document.toml"
display = "display_downstream"

[hooks.upstream]
frame = "frame_upstream"
decode = "decode_upstream"
encode = "encode_upstream"

[hooks.downstream]
frame = "frame_downstream"
decode = "decode_downstream"
encode = "encode_downstream"
