//! 协议脚本作者边界使用的 Rhai 标识符策略。

/// Host API v1 明确拒绝的 Rhai active/reserved 关键字。
pub(crate) const RHAI_RESERVED_WORDS: &[&str] = &[
    "Fn",
    "as",
    "async",
    "await",
    "break",
    "call",
    "case",
    "catch",
    "const",
    "continue",
    "curry",
    "debug",
    "default",
    "do",
    "else",
    "eval",
    "export",
    "false",
    "fn",
    "for",
    "global",
    "go",
    "goto",
    "if",
    "import",
    "in",
    "is",
    "is_def_fn",
    "is_def_var",
    "is_shared",
    "let",
    "loop",
    "match",
    "module",
    "new",
    "nil",
    "null",
    "package",
    "print",
    "private",
    "protected",
    "public",
    "return",
    "shared",
    "spawn",
    "static",
    "super",
    "switch",
    "sync",
    "this",
    "thread",
    "throw",
    "true",
    "try",
    "type_of",
    "until",
    "use",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// 判断名称是否属于 Host API v1 的 Rhai 关键字拒绝集合。
#[must_use]
pub(crate) fn is_rhai_reserved_word(value: &str) -> bool {
    RHAI_RESERVED_WORDS.contains(&value)
}
