[package]
name = "gmofg-proxy-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
encoding_rs.workspace = true
regex = "1.12.2"
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
